#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/jaensite?serverTimezone=Asia/Seoul
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:testdb


#  h2:
#    console:
#      enabled: true